import "~/styles/globals.css";


import { Inter as FontSans } from "next/font/google"
import {
    ClerkProvider,
} from '@clerk/nextjs'

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

import { cn } from "~/lib/utils"

export default function RootLayout({
    children,
}: {
    children: React.ReactNode,
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className={cn(
                        "min-h-screen bg-background font-sans antialiased dark",
                        fontSans.variable
                    )}
                >
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}

export const metadata = {
    title: "Gratitude List",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};


