import "~/styles/globals.css";


import {
    ClerkProvider,
} from '@clerk/nextjs'
import TopNav from "./_components/TopNav";
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className="bg-extend-main-background">
                    <TopNav />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}

export const metadata = {
    title: "Gratitude List",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};


